In [4]:
DATA_PATH = 'data/lichess_db_standard_rated_2019-04.csv'

In [5]:
import pandas as pd

chunks = []
max = 5
current = 0
for chunk in pd.read_csv(DATA_PATH, chunksize=1000):
    chunks.append(chunk)
    current += 1
    if current == max:
        break

In [6]:
df

,game_id,type,result,white_player,black_player,white_elo,black_elo,time_control,num_ply,termination,...,active_pawn_count,active_queen_count,active_rook_count,is_check,num_legal_moves,opp_bishop_count,opp_knight_count,opp_pawn_count,opp_queen_count,opp_rook_count
0,A41W273q,Blitz,0-1,kizi,ChristinaB4661,1038,1046,180+2,58,Normal,...,8,2,2,0,20,2,2,8,2,2
1,A41W273q,Blitz,0-1,kizi,ChristinaB4661,1038,1046,180+2,58,Normal,...,8,2,2,0,20,2,2,8,2,2
2,A41W273q,Blitz,0-1,kizi,ChristinaB4661,1038,1046,180+2,58,Normal,...,8,2,2,0,29,2,2,8,2,2
3,A41W273q,Blitz,0-1,kizi,ChristinaB4661,1038,1046,180+2,58,Normal,...,8,2,2,0,29,2,2,8,2,2
4,A41W273q,Blitz,0-1,kizi,ChristinaB4661,1038,1046,180+2,58,Normal,...,8,2,2,0,28,2,2,8,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,D5JqAORl,Rapid,0-1,Pohjolan,hoodyguy,1557,1809,600+5,110,Normal,...,3,0,0,0,6,0,1,4,0,1
4996,D5JqAORl,Rapid,0-1,Pohjolan,hoodyguy,1557,1809,600+5,110,Normal,...,4,0,1,0,20,0,0,3,0,0
4997,D5JqAORl,Rapid,0-1,Pohjolan,hoodyguy,1557,1809,600+5,110,Normal,...,3,0,0,1,2,0,1,4,0,1
4998,D5JqAORl,Rapid,0-1,Pohjolan,hoodyguy,1557,1809,600+5,110,Normal,...,4,0,1,0,25,0,0,3,0,0
4999,D5JqAORl,Rapid,0-1,Pohjolan,hoodyguy,1557,1809,600+5,110,Normal,...,3,0,0,0,6,0,1,4,0,1

In [7]:
keys = df.keys()
keys

Index(['game_id', 'type', 'result', 'white_player', 'black_player',
       'white_elo', 'black_elo', 'time_control', 'num_ply', 'termination',
       'white_won', 'black_won', 'no_winner', 'move_ply', 'move', 'cp',
       'cp_rel', 'cp_loss', 'is_blunder_cp', 'winrate', 'winrate_elo',
       'winrate_loss', 'is_blunder_wr', 'opp_winrate', 'white_active',
       'active_elo', 'opponent_elo', 'active_won', 'is_capture', 'clock',
       'opp_clock', 'clock_percent', 'opp_clock_percent', 'low_time', 'board',
       'active_bishop_count', 'active_knight_count', 'active_pawn_count',
       'active_queen_count', 'active_rook_count', 'is_check',
       'num_legal_moves', 'opp_bishop_count', 'opp_knight_count',
       'opp_pawn_count', 'opp_queen_count', 'opp_rook_count'],
      dtype='object')

In [8]:
small_df = df[['game_id', 'type', 'white_elo', 'black_elo', 'time_control','move_ply', 'white_active', 'white_won', 'black_won', 'no_winner', 'move', 'cp', 'cp_rel', 'cp_loss', 'is_blunder_cp','low_time','board', 'is_check']]

In [9]:
df['type'].value_counts()

type
Blitz        2806
Rapid         993
Bullet        881
Classical     320
Name: count, dtype: int64

In [10]:
small_df = small_df[(small_df['white_active']) & (small_df['type'].isin(['Blitz', 'Rapid']))]
small_df

,game_id,type,white_elo,black_elo,time_control,move_ply,white_active,white_won,black_won,no_winner,move,cp,cp_rel,cp_loss,is_blunder_cp,low_time,board,is_check
0,A41W273q,Blitz,1038,1046,180+2,0,True,False,True,False,e2e4,0.10,0.10,-0.02,False,False,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,0
2,A41W273q,Blitz,1038,1046,180+2,2,True,False,True,False,g1f3,0.37,0.37,0.14,False,False,rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBN...,0
4,A41W273q,Blitz,1038,1046,180+2,4,True,False,True,False,f3e5,0.76,0.76,0.24,False,False,rnbqkbnr/ppp2ppp/8/3pp3/4P3/5N2/PPPP1PPP/RNBQK...,0
6,A41W273q,Blitz,1038,1046,180+2,6,True,False,True,False,e5f3,3.32,3.32,3.57,True,False,rnbqkbnr/ppp3pp/5p2/3pN3/4P3/8/PPPP1PPP/RNBQKB...,0
8,A41W273q,Blitz,1038,1046,180+2,8,True,False,True,False,f1b5,2.60,2.60,1.17,False,False,rnbqkbnr/ppp4p/5p2/3p2p1/4P3/5N2/PPPP1PPP/RNBQ...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4991,D5JqAORl,Rapid,1557,1809,600+5,88,True,False,True,False,d3c3,NaN,-inf,NaN,False,False,8/7p/n2p2p1/P3kp2/1rP4P/3K4/8/8 w - - 0 45,0
4993,D5JqAORl,Rapid,1557,1809,600+5,90,True,False,True,False,c3d3,NaN,-inf,NaN,False,False,8/7p/n2p2p1/P3k3/1rP2p1P/2K5/8/8 w - - 0 46,0
4995,D5JqAORl,Rapid,1557,1809,600+5,92,True,False,True,False,d3e3,NaN,-inf,NaN,False,False,8/7p/n2p2p1/P3k3/1rP4P/3K1p2/8/8 w - - 0 47,0
4997,D5JqAORl,Rapid,1557,1809,600+5,94,True,False,True,False,e3f2,NaN,-inf,NaN,False,False,8/7p/n2p2p1/P3k3/2P4P/1r2Kp2/8/8 w - - 2 48,1
4999,D5JqAORl,Rapid,1557,1809,600+5,96,True,False,True,False,f2g3,NaN,-inf,NaN,False,False,8/8/n2p2pp/P3k3/2P4P/1r3p2/5K2/8 w - - 0 49,0

In [11]:
TRUE_FINAL_DATA_PATH = "data/true_final_data.csv"
small_df.to_csv(TRUE_FINAL_DATA_PATH, columns=['board', 'move'])

In [12]:
import sqlite3
def create_sqlite_database(filename):
    """ create a database connection to an SQLite database """
    conn = None
    try:
        conn = sqlite3.connect(filename)
        print(sqlite3.sqlite_version)
    except sqlite3.Error as e:
        print(e)
    finally:
        if conn:
            conn.close()

In [35]:
SQLITE_PATH = "./data/database2.db"

In [13]:
create_sqlite_database(SQLITE_PATH)

3.45.3

In [37]:
def add_csv_data(df, db):
    conn = sqlite3.connect(db)
    df.to_sql("moves", conn, if_exists='append', index=False)
    conn.close()

In [38]:
add_csv_data(df, SQLITE_PATH)

In [36]:
def execute_query(db, query):
    conn = sqlite3.connect(db)
    cur = conn.cursor()
    cur.execute(query)
    rows = cur.fetchall()
    conn.close()
    return rows

In [39]:
rows = execute_query(SQLITE_PATH, "select * from moves")

In [40]:
len(rows)

5000